# Generated by Django 3.2.11 on 2022-01-12 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0004_method_protocol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='method',
            table='method',
        ),
        migrations.AlterModelTable(
            name='protocol',
            table='protocol',
        ),
    ]
