# Generated by Django 3.2.11 on 2022-01-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0006_alter_protocol_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='protocol',
            table=None,
        ),
    ]
