# Generated by Django 3.2.11 on 2022-01-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0007_alter_protocol_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
        migrations.AlterModelTable(
            name='api',
            table=None,
        ),
        migrations.AlterModelTable(
            name='case',
            table=None,
        ),
        migrations.AlterModelTable(
            name='collection',
            table=None,
        ),
        migrations.AlterModelTable(
            name='method',
            table=None,
        ),
        migrations.AlterModelTable(
            name='result',
            table=None,
        ),
    ]
