# Generated by Django 3.2.11 on 2022-01-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0008_auto_20220112_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='host',
            field=models.CharField(default='no_host_provided', max_length=20),
        ),
        migrations.AlterField(
            model_name='api',
            name='order',
            field=models.IntegerField(blank=True, default=999, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
