# Generated by Django 3.2.11 on 2022-01-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0009_auto_20220124_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='host',
            field=models.CharField(max_length=20),
        ),
    ]
