# Generated by Django 3.2.11 on 2022-01-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0010_auto_20220124_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='port',
            field=models.IntegerField(default=8000),
            preserve_default=False,
        ),
    ]
