# Generated by Django 3.2.11 on 2022-01-24 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0011_alter_api_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiservice.method'),
        ),
        migrations.AlterField(
            model_name='api',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiservice.protocol'),
        ),
    ]
