# Generated by Django 3.2.11 on 2022-01-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0012_auto_20220124_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='collection',
            name='order',
            field=models.IntegerField(blank=True, default=999, null=True),
        ),
    ]
